import LeftSideBar from '@/components/LeftSideBar';
import '@/styles/globals.css';
import { Suspense } from 'react';
import Loading from './Loading';
import ToastContainerWrapper from '@/components/ToastContainer';
import { Providers } from '@/context/Providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html className='h-full'>
      <body className='h-full w-full flex'>
        <Providers>
          <Suspense fallback={<Loading />}>
            <div className='h-full w-full flex items-center justify-center bg-base-200'>
              {children}
            </div>
          </Suspense>
          <ToastContainerWrapper />
        </Providers>
      </body>
    </html>
  );
}
