import LeftSideBar from '@/components/LeftSideBar';
import { Suspense } from 'react';
import Loading from '../Loading';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function LoggedInLayout({ children }) {
  return (
    <div className='flex w-full h-full'>
      <LeftSideBar>
        <Suspense fallback={<Loading />}>
          <div className=' xs:pl-0 h-full w-full flex items-center justify-center bg-base-200'>
            {children}
          </div>
        </Suspense>
      </LeftSideBar>
    </div>
  );
}
