import LeftSideBar from '@/components/LeftSideBar';
import '@/styles/globals.css';
import { Suspense } from 'react';
import Loading from '../Loading';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function LoggedInLayout({ children }) {
  function LeftSideBarLoading() {
    return (
      <div
        className={` bg-primary h-screen p-5 pt-8 w-60 duration-500 ease-in-out relative `}
      >
        <Loading />
      </div>
    );
  }
  return (
    <div className='flex'>
      <Suspense fallback={LeftSideBarLoading()}>
        <LeftSideBar />
      </Suspense>
      <div className='flex-1 p-4'>
        <Suspense fallback={<Loading />}>
          <div className='pl-10 h-full w-full flex items-center justify-center bg-base-200'>
            {children}
          </div>
        </Suspense>
      </div>
    </div>
  );
}
